--DDL - Data Defition Language
CREATE DATABASE Exercicio_1_2
USE Exercicio_1_2

CREATE TABLE Cliente
(
	IdCliente INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(32) NOT NULL,
	Cpf CHAR(11) NOT NULL,
)

CREATE TABLE Empresa
(
	IdEmpresa INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(32) NOT NULL UNIQUE
)

CREATE TABLE Marca
(
	IdMarca INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(32) NOT NULL UNIQUE
)

CREATE TABLE Modelo
(
	IdModelo INT PRIMARY KEY IDENTITY,
	IdMarca INT FOREIGN KEY REFERENCES Marca(IdMarca),
	Nome VARCHAR(32) NOT NULL UNIQUE
)

CREATE TABLE Veiculo
(
	IdVeiculo INT PRIMARY KEY IDENTITY,
	IdAluguel INT FOREIGN KEY REFERENCES Aluguel(IdAluguel) UNIQUE,
	IdModelo INT FOREIGN KEY REFERENCES Modelo(IdModelo) NOT NULL,
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa(IdEmpresa) NOT NULL
)

CREATE TABLE Aluguel
(
	IdAluguel INT PRIMARY KEY IDENTITY,
	IdCliente INT FOREIGN KEY REFERENCES Cliente(IdCliente),
)

SELECT * FROM Cliente
SELECT * FROM Empresa
SELECT * FROM Aluguel
SELECT * FROM Marca
SELECT * FROM Modelo
SELECT * FROM Veiculo